/*
 * Copyright (c) 2026 Tomasz Zurawski
 * SPDX-License-Identifier: AGPL-3.0-only
 */
package io.github.mgrtomaszzurawski.allegro.sdk.domain.offerextras.model;

/**
 * How an offer's title translation was produced.
 *
 * @since 0.2.0
 */
public enum OfferTranslationType {

    /** Machine-generated by Allegro. */
    AUTO,

    /** Provided by the seller. */
    MANUAL,

    /** The offer's original (base) language text. */
    BASE,

    /** A value Allegro introduced that this SDK version does not model yet. */
    UNKNOWN
}
