/*
 * Copyright (c) 2026 Tomasz Zurawski
 * SPDX-License-Identifier: AGPL-3.0-only
 */
package io.github.mgrtomaszzurawski.allegro.sdk.domain.offerextras.model;

import io.github.mgrtomaszzurawski.allegro.client.model.OfferTranslationTypeRaw;
import org.jspecify.annotations.Nullable;

/**
 * How an offer translation was produced — applies to the title, description, and
 * per-product safety-information translations.
 *
 * @since 0.2.0
 */
public enum OfferTranslationType {

    /** Machine-generated by Allegro. */
    AUTO,

    /** Provided by the seller. */
    MANUAL,

    /** The offer's original (base) language text. */
    BASE,

    /** A value Allegro introduced that this SDK version does not model yet. */
    UNKNOWN;

    /**
     * Map the generated Layer-1 translation type, degrading a value Allegro added
     * after this SDK version to {@link #UNKNOWN} rather than failing the read.
     */
    static @Nullable OfferTranslationType fromRaw(@Nullable OfferTranslationTypeRaw raw) {
        if (raw == null) {
            return null;
        }
        try {
            return valueOf(raw.name());
        } catch (IllegalArgumentException unknownType) {
            return UNKNOWN;
        }
    }
}
