/*
 * Copyright (c) 2026 Tomasz Zurawski
 * SPDX-License-Identifier: AGPL-3.0-only
 */
package io.github.mgrtomaszzurawski.allegro.sdk.domain.settings.additionalservices.model;

import io.github.mgrtomaszzurawski.allegro.client.model.AdditionalServicesGroupTranslationWrapperWithTypeRaw;

/**
 * Whether a group translation was entered by the merchant or generated by Allegro.
 *
 * @since 0.3.0
 */
public enum TranslationType {

    /** Provided by the merchant. */
    MANUAL,

    /** Generated automatically by Allegro. */
    AUTO;

    /**
     * Map the generated Layer-1 enum. The wire value and constant name coincide,
     * so an unmapped server value fails loudly via {@link #valueOf(String)}.
     */
    public static TranslationType from(AdditionalServicesGroupTranslationWrapperWithTypeRaw.TypeEnum raw) {
        return valueOf(raw.name());
    }
}
